# Generated by Django 4.2 on 2025-04-08 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reciclagem', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caixa',
            options={'verbose_name': 'Caixa', 'verbose_name_plural': 'Caixas'},
        ),
        migrations.AlterModelOptions(
            name='coleta',
            options={'verbose_name': 'Coleta', 'verbose_name_plural': 'Coletas'},
        ),
        migrations.AlterModelOptions(
            name='coletor',
            options={'verbose_name': 'Coletor', 'verbose_name_plural': 'Coletores'},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name': 'Material', 'verbose_name_plural': 'Materiais'},
        ),
        migrations.AddField(
            model_name='coletor',
            name='faz_parte_cooperativa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coletor',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_coletores/'),
        ),
    ]
