# Generated by Django 5.2 on 2025-04-12 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reciclagem', '0002_alter_caixa_options_alter_coleta_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coletor',
            name='conta_para_deposito',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='coletor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='coletor',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='coletor',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='coletor',
            name='tipo_documento',
            field=models.CharField(choices=[('CPF', 'CPF'), ('RG', 'RG'), ('CNH', 'CNH')], default='CPF', max_length=10),
        ),
    ]
