# Generated by Django 5.2 on 2025-04-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reciclagem', '0003_coletor_conta_para_deposito_coletor_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coletor',
            name='conta_para_deposito',
        ),
        migrations.AddField(
            model_name='coletor',
            name='agencia',
            field=models.CharField(default='0000', max_length=10),
        ),
        migrations.AddField(
            model_name='coletor',
            name='banco',
            field=models.CharField(default='Não informado', max_length=50),
        ),
        migrations.AddField(
            model_name='coletor',
            name='numero_conta',
            field=models.CharField(default='000000', max_length=20),
        ),
        migrations.AddField(
            model_name='coletor',
            name='tipo_conta',
            field=models.CharField(choices=[('corrente', 'Conta Corrente'), ('poupanca', 'Poupança')], default='corrente', max_length=10),
        ),
        migrations.AlterField(
            model_name='coletor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='coletor',
            name='endereco',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='coletor',
            name='telefone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='coletor',
            name='tipo_documento',
            field=models.CharField(choices=[('CPF', 'CPF'), ('RG', 'RG'), ('CNH', 'CNH')], max_length=10),
        ),
    ]
